title: lamachin3
description: lamachin3's blog currently hosting my CTF writeups
theme: just-the-docs

url: https://lamachin3.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
